# -*- coding: utf-8 -*-
"""ipl_analysis.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3PVBzBMhuz9xec9M3HlMGbkjKnuqQDv

#**IPL Cricket Analytics Project**


###**Project Overview**

This project analyzes IPL cricket data using Python, Pandas, NumPy, Matplotlib, and Seaborn. The objective is to uncover insights related to team performance, batting trends, bowling efficiency, toss impact, venue analysis, and match-winning patterns using ball-by-ball IPL data.

#IMPORT LIBRARIES

##Purpose

Import required Python libraries for data analysis and visualization.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""#LOAD DATASETS
##Purpose

Load IPL match-level and ball-by-ball datasets into Python.
"""

matches = pd.read_csv("/content/matches.csv")

deliveries = pd.read_csv("/content/deliveries.csv")

"""#DISPLAY FIRST 5 ROWS OF DATASETS
##Purpose

Check dataset structure and understand available columns.
"""

matches.head()

deliveries.head()

"""#CHECK DATASET COLUMNS
##Purpose

Understand important columns before merging datasets.
"""

print(matches.columns)

print(deliveries.columns)

"""#MERGE MATCHES AND DELIVERIES DATASETS
##Purpose

Combine match-level and ball-by-ball datasets using match identifiers
"""

ipl = deliveries.merge(
    matches,
    left_on='match_id',
    right_on='id',
    how='inner'
)

"""##Insight

This merge creates a unified dataset containing player, team, venue, and match-level information.

#DISPLAY MERGED DATASET
##Purpose

Verify whether datasets merged successfully.
"""

ipl.head()

"""#CREATE TOTAL RUNS FEATURE
##Purpose

Calculate total runs scored on every delivery.
"""

ipl['total_runs'] = (
    ipl['batsman_runs']
    + ipl['extra_runs']
)

"""#MOST SUCCESSFUL IPL TEAMS ANALYSIS
##Purpose

Identify teams with the highest number of wins.
"""

team_wins = ipl['winner'].value_counts()

team_wins

"""#VISUALIZATION OF TEAM WINS
##Purpose

Visualize team performance using bar charts.
"""

plt.figure(figsize=(12,6))
team_wins.plot(kind='bar')
plt.title('Most Successful IPL Teams')
plt.xlabel('Teams')
plt.ylabel('Wins')
plt.xticks(rotation=45)

plt.show()

"""#TOP RUN SCORERS ANALYSIS
##Purpose

Identify the highest run-scoring batters in IPL history.
"""

runs = ipl.groupby(
    'batter'
)['batsman_runs'].sum().sort_values(
    ascending=False
).head(10)

runs

"""#VISUALIZATION OF TOP RUN SCORERS
##Purpose

Visualize the top-performing batters.
"""

plt.figure(figsize=(12,6))
runs.plot(kind='bar')
plt.title('Top Run Scorers')
plt.xlabel('Players')
plt.ylabel('Runs')

plt.show()

"""#TOP WICKET TAKERS ANALYSIS
##Purpose

Identify bowlers with the highest wickets in IPL history.
"""

wickets = ipl[
    ipl['dismissal_kind'].notnull()
]

wicket_count = wickets.groupby(
    'bowler'
).size().sort_values(
    ascending=False
).head(10)

wicket_count

"""#VISUALIZATION OF TOP WICKET TAKERS
##Purpose

Visualize bowling performance using bar charts.
"""

plt.figure(figsize=(12,6))
wicket_count.plot(kind='bar')
plt.title('Top Wicket Takers')
plt.xlabel('Bowlers')
plt.ylabel('Wickets')

plt.show()

"""#TOSS IMPACT ANALYSIS
##Purpose

Analyze how often toss winners also win the match.
"""

toss_match = ipl[
    ipl['toss_winner']
    == ipl['winner']
]

impact = (
    len(toss_match)
    / len(ipl)
) * 100

print(impact)

"""#SEASON-WISE RUNS ANALYSIS
##Purpose

Analyze scoring trends across IPL seasons.
"""

season_runs = ipl.groupby(
    'season'
)['total_runs'].sum()

season_runs

"""#Visualization"""

plt.figure(figsize=(12,6))

season_runs.plot(
    kind='line',
    marker='o'
)

plt.title('Season Wise Total Runs')
plt.xlabel('Season')
plt.ylabel('Runs')
plt.grid(True)

plt.show()

"""#Toss Decision Analysis
##Purpose

Analyze whether teams prefer batting or bowling after winning the toss.
"""

toss_decision = matches[
    'toss_decision'
].value_counts()

toss_decision

"""#Visualization"""

plt.figure(figsize=(6,6))
toss_decision.plot(
    kind='pie',
    autopct='%1.1f%%'
)
plt.ylabel('')
plt.title('Toss Decision Distribution')

plt.show()

"""#VENUE ANALYSIS
##Purpose

Identify high-scoring IPL venues
"""

venue_scores = ipl.groupby(
    'venue'
)['total_runs'].mean().sort_values(
    ascending=False
).head(10)

venue_scores

"""#Visualization"""

plt.figure(figsize=(12,6))
venue_scores.plot(kind='bar')
plt.title('Highest Scoring Venues')
plt.xlabel('Venue')
plt.ylabel('Average Runs')

plt.show()

"""#Chasing vs Defending Analysis
##Purpose

Compare match outcomes while chasing versus defending targets
"""

matches['result'] = np.where(
    matches['winner']
    == matches['team2'],
    'Chasing',
    'Defending'
)

result_analysis = matches[
    'result'
].value_counts()

result_analysis

"""#Visualization"""

plt.figure(figsize=(6,6))
result_analysis.plot(
    kind='pie',
    autopct='%1.1f%%'
)
plt.ylabel('')
plt.title('Chasing vs Defending Wins')

plt.show()

"""# Best Strike Rates

##Minimum 1000 runs
"""

batsman = ipl.groupby(
    'batter'
).agg({
    'batsman_runs':'sum',
    'ball':'count'
})

batsman = batsman[
    batsman['batsman_runs'] > 1000
]

batsman['strike_rate'] = (
    batsman['batsman_runs']
    / batsman['ball']
) * 100

batsman = batsman.sort_values(
    by='strike_rate',
    ascending=False
).head(10)

batsman

"""#Best Economy Bowlers

##Minimum 500 balls
"""

bowler = ipl.groupby(
    'bowler'
).agg({
    'total_runs':'sum',
    'ball':'count'
})

bowler = bowler[
    bowler['ball'] > 500
]

bowler['overs'] = (
    bowler['ball'] / 6
)

bowler['economy'] = (
    bowler['total_runs']
    / bowler['overs']
)

best_economy = bowler.sort_values(
    by='economy'
).head(10)

best_economy

"""#FEATURE ENGINEERING
##Purpose

Create advanced analytical features for deeper insights.

#CREATE BOUNDARY FEATURE
##Purpose

Identify deliveries resulting in boundaries.
"""

ipl['is_boundary'] = np.where(
    ipl['batsman_runs'].isin([4,6]),
    1,
    0
)

batter_stats = ipl.groupby(
    'batter'
).agg({
    'batsman_runs':'sum',
    'ball':'count',
    'is_boundary':'sum'
})

batter_stats['boundary_percent'] = (
    batter_stats['is_boundary']
    / batter_stats['ball']
) * 100

batter_stats = batter_stats[
    batter_stats['batsman_runs'] > 2000
]

batter_stats.sort_values(
    by='boundary_percent',
    ascending=False
).head(10)

"""#CREATE DOT BALL FEATURE
##Purpose

Identify deliveries where no runs were scored.
"""

ipl['is_dot'] = np.where(
    ipl['total_runs'] == 0,
    1,
    0
)

bowler_stats = ipl.groupby(
    'bowler'
).agg({
    'ball':'count',
    'is_dot':'sum'
})

bowler_stats = bowler_stats[
    bowler_stats['ball'] > 500
]

bowler_stats['dot_ball_percent'] = (
    bowler_stats['is_dot']
    / bowler_stats['ball']
) * 100

bowler_stats.sort_values(
    by='dot_ball_percent',
    ascending=False
).head(10)

"""# CREATE MATCH PHASE FEATURE

## Purpose

Divide innings into Powerplay,
Middle Overs, and Death Overs.
"""

def phase(over):
    if over <= 6:
        return 'Powerplay'
    elif over <= 15:
        return 'Middle Overs'
    else:
        return 'Death Overs'

ipl['phase'] = ipl['over'].apply(phase)

"""# PHASE-WISE SCORING ANALYSIS

## Purpose

Analyze scoring trends across
different match phases.
"""

phase_runs = ipl.groupby(
    'phase'
)['total_runs'].sum()

phase_runs

"""# VISUALIZATION OF PHASE-WISE RUNS

## Purpose

Visualize runs scored in Powerplay,
Middle Overs, and Death Overs.
"""

phase_runs.plot(kind='bar')
plt.title('Runs Across Match Phases')
plt.ylabel('Runs')

plt.show()

"""# DEATH OVERS BATTING ANALYSIS

## Purpose

Identify the best finishers and
high-pressure batters in IPL.
"""

death_overs = ipl[
    ipl['phase'] == 'Death Overs'
]

death_batters = death_overs.groupby(
    'batter'
)['batsman_runs'].sum().sort_values(
    ascending=False
).head(10)

death_batters

"""# PLAYER CONSISTENCY ANALYSIS

## Purpose

Measure average runs scored per match
to identify consistent batters.

## Insight

Consistent players contribute more
reliably to team success.
"""

player_match_runs = ipl.groupby(
    ['batter','match_id']
)['batsman_runs'].sum().reset_index()

consistency = player_match_runs.groupby(
    'batter'
)['batsman_runs'].mean().sort_values(
    ascending=False
).head(10)

consistency

"""# TEAM DEPENDENCY ANALYSIS

## Purpose

Analyze which teams rely heavily
on individual players for scoring.

## Insight

Certain teams are highly dependent
on star players for run production.
"""

team_player_runs = ipl.groupby(
    ['batting_team','batter']
)['batsman_runs'].sum().reset_index()

team_totals = ipl.groupby(
    'batting_team'
)['batsman_runs'].sum().reset_index()

dependency = pd.merge(
    team_player_runs,
    team_totals,
    on='batting_team'
)

dependency['dependency_percent'] = (
    dependency['batsman_runs_x']
    / dependency['batsman_runs_y']
) * 100

dependency.sort_values(
    by='dependency_percent',
    ascending=False
).head(10)

"""# VENUE ADVANTAGE ANALYSIS

## Purpose

Identify teams performing strongly
at specific IPL venues.

## Insight

Home venue familiarity significantly
improves team performance.
"""

venue_advantage = matches.groupby(
    ['venue','winner']
).size().reset_index(name='wins')

venue_advantage.sort_values(
    by='wins',
    ascending=False
).head(10)

"""# WINNING PATTERN ANALYSIS

## Purpose

Compare batting-first wins
versus chasing wins.
"""

matches['win_type'] = np.where(
    matches['winner'] == matches['team1'],
    'Bat First',
    'Chasing'
)

matches['win_type'].value_counts()

"""# VISUALIZATION OF WINNING PATTERNS

## Purpose

Visualize IPL winning patterns
using a pie chart.
"""

matches['win_type'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)
plt.ylabel('')
plt.title('Winning Pattern')

plt.show()

"""# DEATH OVERS BOWLING ANALYSIS

## Purpose

Identify bowlers with the best
economy rates in death overs.

## Insight

Economical death-over bowlers play
a critical role in controlling matches.
"""

death_bowling = ipl[
    ipl['phase'] == 'Death Overs'
]

death_bowler_stats = death_bowling.groupby(
    'bowler'
).agg({
    'total_runs':'sum',
    'ball':'count'
})

death_bowler_stats['economy'] = (
    death_bowler_stats['total_runs']
    / (death_bowler_stats['ball']/6)
)

death_bowler_stats.sort_values(
    by='economy'
).head(10)

"""# CORRELATION ANALYSIS

## Purpose

Analyze relationships between
important numerical variables.
"""

numeric_cols = [
    'batsman_runs',
    'extra_runs',
    'total_runs',
    'is_boundary',
    'is_dot'
]
correlation = ipl[
    numeric_cols
].corr()

correlation

"""# CORRELATION HEATMAP

## Purpose

Visualize feature correlations
using a heatmap.
"""

plt.figure(figsize=(8,6))

sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm'
)

plt.title('Correlation Heatmap')

plt.show()

"""#MACHINE LEARNING MODEL
##Purpose

Predict IPL match winners using historical match data.

# IMPORT MACHINE LEARNING LIBRARIES

## Purpose

Import libraries required for
IPL match prediction modeling.
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

"""# SELECT IMPORTANT FEATURES

## Purpose

Select match-related variables
for machine learning prediction.
"""

ml_data = matches[[
    'team1',
    'team2',
    'toss_winner',
    'toss_decision',
    'venue',
    'winner'
]]

"""# REMOVE NULL VALUES

## Purpose

Remove missing values before
training the machine learning model.
"""

ml_data = ml_data.dropna()

"""# DISPLAY MACHINE LEARNING DATA

## Purpose

Verify processed machine learning dataset.
"""

ml_data.head()

"""# LABEL ENCODING

## Purpose

Convert categorical text data
into numerical format.
"""

encoder = LabelEncoder()
for column in ml_data.columns:

    ml_data[column] = encoder.fit_transform(
        ml_data[column]
    )

"""# DEFINE FEATURES AND TARGET

## Purpose

Separate independent variables
and target variable.
"""

X = ml_data.drop(
    'winner',
    axis=1
)
y = ml_data['winner']

"""# TRAIN TEST SPLIT

## Purpose

Split dataset into training
and testing sets.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""# BUILD RANDOM FOREST MODEL

## Purpose

Create a Random Forest classifier
for IPL match prediction.
"""

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

"""# TRAIN MACHINE LEARNING MODEL

## Purpose

Train prediction model using
historical IPL match data.
"""

model.fit(
    X_train,
    y_train
)

"""# MAKE MATCH PREDICTIONS

## Purpose

Predict IPL match winners
on unseen test data.
"""

predictions = model.predict(
    X_test
)

"""# MODEL ACCURACY EVALUATION

## Purpose

Measure prediction accuracy
of the machine learning model.
"""

accuracy = accuracy_score(
    y_test,
    predictions
)
print(
    f'Accuracy: {accuracy:.2f}'
)

"""# CLASSIFICATION REPORT

## Purpose

Evaluate model precision,
recall, and F1-score.
"""

print(
    classification_report(
        y_test,
        predictions
    )
)

"""# CONFUSION MATRIX

## Purpose

Analyze prediction performance
across different classes.
"""

cm = confusion_matrix(
    y_test,
    predictions
)
cm

"""# VISUALIZATION OF CONFUSION MATRIX

## Purpose

Visualize prediction accuracy
using heatmap representation.
"""

plt.figure(figsize=(10,8))
sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')

plt.show()

"""# FEATURE IMPORTANCE ANALYSIS

## Purpose

Identify the most influential
features affecting match outcomes.

## Insight

Venue and toss decisions strongly
influence IPL match results.
"""

importance = pd.Series(
    model.feature_importances_,
    index=X.columns
)
importance.sort_values(
    ascending=False
)

"""# VISUALIZATION OF FEATURE IMPORTANCE

## Purpose

Visualize important match-winning
factors in IPL prediction.
"""

importance.sort_values().plot(
    kind='barh'
)
plt.title('Feature Importance')
plt.show()

"""# CUSTOM MATCH PREDICTION

## Purpose

Predict outcome for a custom
IPL match scenario.
"""

sample = pd.DataFrame([[
    0,
    1,
    0,
    1,
    5
]], columns=X.columns)

prediction = model.predict(sample)

print("Predicted Winner Code:", prediction[0])



"""# PROJECT CONCLUSION

This IPL Cricket Analytics project successfully analyzed historical IPL match and ball-by-ball data using Python, Pandas, NumPy, Matplotlib, and Machine Learning techniques.

Key achievements:
- Performed data cleaning and preprocessing
- Conducted exploratory data analysis (EDA)
- Built advanced cricket KPIs
- Analyzed batting and bowling performance
- Studied toss impact and venue trends
- Developed a Random Forest match prediction model
- Generated business insights using data visualization

The project demonstrates end-to-end Data Analytics workflow including feature engineering, statistical analysis, visualization, and predictive modeling.
"""